sudo: false
language: ruby
env:
  global:
    - PQ_REST_API_HOST=http://localhost:8888
    - CODECLIMATE_REPO_TOKEN=08183fa3b285d981f273ace1c809c402810db3221b1060023a6db8633ac5b8cb
    - DEVISE_SENDER=no-reply@digital.justice.gov.uk
    - RAILS_ENV=test
    - TEST_USER_PASS=test
rvm:
  - 2.1.2
before_script:
  - psql -c 'create role pq login createdb;' -U postgres
addons:
  postgresql: 9.3
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
  - bundle exec rspec features
#notifications:
#  hipchat:
#    rooms:
#      secure: <token_here>
#    format: html
#    template:
#      - '%{message} (<a href="%{build_url}">details</a>/<a href="%{compare_url}">changes</a>) - build #%{build_number}, branch <a href="https://github.com/%{repository}/tree/%{branch}">%{branch}</a>; of %{repository}'
addons:
  postgresql: 9.3
